### ISSUE TITLE
Undefined local variable or method `collection' for Mongo::Lock::Queries instance

### ISSUE THREAD

**Issue by kliput** [trakio/mongo-lock#7]
Hello,

I'm trying to execute this fragment of code in my tests:

```
collection = MongoActiveRecord.get_collection('locks')
Mongo::Lock.configure collection: collection

Mongo::Lock.configure do |config|
    config.timeout_in = false # timeout_in in seconds on acquisition; this defaults to false ie no time limit.
    config.limit = 3 # The limit on the number of acquisition attempts; this defaults to 100.
    config.frequency = 2 # Frequency in seconds for acquisition attempts ; this defaults to 1.
    end

Mongo::Lock.ensure_indexes

Mongo::Lock.acquire 'job' do |lock|
    puts 'hello world'
end
```

But it fails on Mongo::Lock.acquire:

```
NameError: undefined local variable or method `collection' for #<Mongo::Lock::Queries:0x0000000290c138>
    test/models/lock_test.rb:58:in `test_lock_write'
```

Exception is thrown from lib/mongo-lock/queries.rb:

```
      def find_already_acquired
        collection.find({
          key: key,
          owner: lock.configuration.owner,
          expires_at: { '$gt' => Time.now }
        })
      end
```

Using Ruby 2.1.1p76 (2014-02-24 revision 45161) and mongo-lock v1.1.0 (installed with bundle).
I'm sure that collection object set in configuration is valid.

**Comment by msaspence** [comment]
Hey @kliput 

Sorry for the delay on this, must have missed the notification.

Will try and take a look at this later today.

**Comment by msaspence** [comment]
Just pushed 1.1.1 to fix this give it a whirl

**Comment by kliput** [comment]
Thanks for fix, but now I can't launch 1.1.1 because some it cannot load some dependencies. First I had to add 'mongoid' manually to Gemfile, because it wasn't installed automatically. Now I'm getting:

```
cannot load such file -- mongoid/railties/document
```

I've added 'document' to Gemfile and executed bundle install, but it still complains about it.
Can you check if dependencies are correctly defined, or I'm doing something wrong?

**Comment by msaspence** [comment]
Sorry, railstie stuff wasn't included in tests (still not covered, but is now required in) so I missed all that mongoid stuff that I put in when originally planning to support mongoid collections

**Comment by msaspence** [comment]
@kliput I just published an update that supports moped collections. I haven't tested this in production yet, proceed with caution.
